exceptiongroup/__init__.py,sha256=xykZT7YBz3vr7EO7tigtJNW6RHO7ogL6mNROpO_DOkM,538
exceptiongroup/_catch.py,sha256=REnsogZqBjgWJRVfzkLcUo5Xn7_ogX9oMMnIcWGF-LM,3591
exceptiongroup/_exceptions.py,sha256=Ii53l8ly-jjn64UIApU2x3kThLBhpYqlWHUTo0b4d0U,6688
exceptiongroup/_formatting.py,sha256=lElDdgXud0D-mZnQdCIPaqgzlIH0xhZra3DexLrzYYw,7548
exceptiongroup/_version.py,sha256=8gCN2R0Yvr735jsjV5uCga66Gp8MW0IaUuutyxP1iRo,145
exceptiongroup/py.typed,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
exceptiongroup-1.0.0rc4.dist-info/LICENSE,sha256=blBw12UDHgrUA6HL-Qrm0ZoCKPgC4yC3rP9GCqcu1Hw,3704
exceptiongroup-1.0.0rc4.dist-info/WHEEL,sha256=hfJxL4BjFtcsLdc9M7QmgP-fgzeNDbKrgf8rndEmLgc,81
exceptiongroup-1.0.0rc4.dist-info/METADATA,sha256=KPh2VL8cvaITDroMJLXr6VWZhEI0JgkSK3ikKrKmmMs,4429
exceptiongroup-1.0.0rc4.dist-info/RECORD,,
