exceptiongroup/__init__.py,sha256=xykZT7YBz3vr7EO7tigtJNW6RHO7ogL6mNROpO_DOkM,538
exceptiongroup/_catch.py,sha256=REnsogZqBjgWJRVfzkLcUo5Xn7_ogX9oMMnIcWGF-LM,3591
exceptiongroup/_exceptions.py,sha256=Ii53l8ly-jjn64UIApU2x3kThLBhpYqlWHUTo0b4d0U,6688
exceptiongroup/_formatting.py,sha256=Ngn3RdHuYgHbqOIZ2p9b69zQyKC9NZwj1CQ7TipgHPg,9047
exceptiongroup/_version.py,sha256=utyYHY40FytT0yLfsJOZWfJi8qAOnMZYKTnTZfLnZ5U,145
exceptiongroup/py.typed,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
exceptiongroup-1.0.0rc5.dist-info/LICENSE,sha256=blBw12UDHgrUA6HL-Qrm0ZoCKPgC4yC3rP9GCqcu1Hw,3704
exceptiongroup-1.0.0rc5.dist-info/WHEEL,sha256=hfJxL4BjFtcsLdc9M7QmgP-fgzeNDbKrgf8rndEmLgc,81
exceptiongroup-1.0.0rc5.dist-info/METADATA,sha256=X9Z-P4JHr1kRVq73WoJdx8OKNf5C0MghfJon7B6Z0_s,4429
exceptiongroup-1.0.0rc5.dist-info/RECORD,,
